#+title: How to Install

This document will explain assuming the installation of Yamcs 5.9.3.
If you are installing a different version, please adjust the version
number accordingly.

Furthermore, this explanation assumes the installation of Yamcs on a
Debian Linux-based distribution.

* Install Yamcs

  * Download Yamcs rpm package from [[https://github.com/yamcs/yamcs/releases][yamcs github]]
    #+begin_example
    wget https://github.com/yamcs/yamcs/releases/download/yamcs-5.12.0/yamcs-5.12.0-1.x86_64.rpm
    #+end_example

  * Install alien for convert rpm to deb (Only the first time)

    Note: Some warnings will appear, but please ignore them.
    #+begin_example
    sudo apt-get install alien
    #+end_example

  * Convert rpm to deb
    #+begin_example
    sudo alien --script -d -k yamcs-5.12.0-1.x86_64.rpm
    #+end_example

  * Install deb
    #+begin_example
    sudo dpkg -i yamcs_5.12.0-1_amd64.deb
    #+end_example

* Install Java runtime

  * Install java runtime package

    Note: You need to install JDK 17 or higher.
    #+begin_example
    sudo apt install openjdk-17-jdk
    #+end_example

* Preparing for configuration and mdb files

  * Create working directory (Any name is OK)
    #+begin_example
    mkdir ~/yamcs_work
    #+end_example

  * Clone repository
    #+begin_example
    cd ~/yamcs_work
    git clone https://github.com/spacecubics/scsat1-mcs.git
    #+end_example

  * Make python virtual environment
    #+begin_example
    sudo apt install python-is-python3 python3-pip python3-venv
    python3 -m venv .venv
    source .venv/bin/activate
    #+end_example

  * Install required PIP packages
    #+begin_example
    cd scsat1-mcs
    pip install -r requirements.txt
    #+end_example

  * Install configuration files and mission data bases using script
    #+begin_example
    ./scripts/inst_cfg_mdb.sh ~/yamcs_work
    #+end_example


* Implementing additional features
  * Install java build tool
    #+begin_example
    sudo apt install maven
    #+end_example

  * Copy the created jar file to the Yamcs library directory
    #+begin_example
    sudo cp scsat1-packet/target/scsat1_packet_preprpcessor-1.0.0.jar /opt/yamcs/lib/
    sudo cp file-transfer/target/scsat1_file_transfer-1.0.0.jar /opt/yamcs/lib/
    #+end_example

  * Configure the yaml files
    * yamcs.yaml
      #+begin_example
      buckets:
        - name: scsat1
          path: /bucket # Specify the path where the transfer files are stored
      #+end_example

    * yamcs.scsat1.yaml
      #+begin_example
      services:
          - class: org.yamcs.cfdp.Scsat1Service
            name: scsat1_file_transfer
            args:
                sleepBetweenPdus: 1000
                localEntities:
                  - name: yamcs
                    id: 1
                    bucket: scsat1
                remoteEntities:
                  - name: main
                    id: 8
                  - name: adcs
                    id: 16
                canChangePduDelay: true
                canChangeOffset: true
      #+end_example

      Options:
      - sleepBetweenPdus: Specifies the default transfer interval in milliseconds. (Default: 1000)
      - canChangePduDelay: Set to true to allow specifying the transfer interval for each transfer. (Default: false)
      - canChangeOffset: Set to true to allow specifying the start offset for each transfer. (Default: false)

* Run Yamcs

  * Run
    #+begin_example
    /opt/yamcs/bin/yamcsd --etc-dir ~/yamcs_work/etc/
    #+end_example
