pdf-name: "./main.pdf"
csv-dir: "./main_csv"
parameters:
  - name: "/SCSAT1/MAIN/OBC_1_TEMP"
    status: "/SCSAT1/MAIN/OBC_1_TEMP_Status"
  - name: "/SCSAT1/MAIN/OBC_2_TEMP"
    status: "/SCSAT1/MAIN/OBC_2_TEMP_Status"
  - name: "/SCSAT1/MAIN/OBC_3_TEMP"
    status: "/SCSAT1/MAIN/OBC_3_TEMP_Status"
  - name: "/SCSAT1/MAIN/OBC_XADC_TEMP"
    status: "/SCSAT1/MAIN/OBC_XADC_TEMP_Status"
  - name: "/SCSAT1/MAIN/IOBOARD_1_TEMP"
    status: "/SCSAT1/MAIN/IOBOARD_1_TEMP_Status"
  - name: "/SCSAT1/MAIN/IOBOARD_2_TEMP"
    status: "/SCSAT1/MAIN/IOBOARD_2_TEMP_Status"
  - name: "/SCSAT1/MAIN/X_PLUS_TEMP"
    status: "/SCSAT1/MAIN/X_PLUS_TEMP_Status"
  - name: "/SCSAT1/MAIN/X_MINUS_TEMP"
    status: "/SCSAT1/MAIN/X_MINUS_TEMP_Status"
  - name: "/SCSAT1/MAIN/Y_PLUS_TEMP"
    status: "/SCSAT1/MAIN/Y_PLUS_TEMP_Status"
  - name: "/SCSAT1/MAIN/Y_MINUS_TEMP"
    status: "/SCSAT1/MAIN/Y_MINUS_TEMP_Status"
  - name: "/SCSAT1/MAIN/SUNSENS_Y_PLUS_TEMP"
    status: "/SCSAT1/MAIN/SUNSENS_Y_PLUS_TEMP_Status"
  - name: "/SCSAT1/MAIN/SUNSENS_Y_MINUS_TEMP"
    status: "/SCSAT1/MAIN/SUNSENS_Y_MINUS_TEMP_Status"
  - name: "/SCSAT1/MAIN/MGNM_X_PLUS_TEMP"
    status: "/SCSAT1/MAIN/MGNM_X_PLUS_TEMP_Status"
  - name: "/SCSAT1/MAIN/MGNM_X_MINUS_TEMP"
    status: "/SCSAT1/MAIN/MGNM_X_MINUS_TEMP_Status"
  - name: "/SCSAT1/MAIN/DSTRX3_HK_TEMP"
    status: "/SCSAT1/MAIN/DSTRX3_HK_Status"
  - name: "/SCSAT1/MAIN/OBC_1V0_Shunt"
    status: "/SCSAT1/MAIN/OBC_1V0_Shunt_Status"
  - name: "/SCSAT1/MAIN/OBC_1V0_Bus"
    status: "/SCSAT1/MAIN/OBC_1V0_Bus_Status"
  - name: "/SCSAT1/MAIN/OBC_1V8_Shunt"
    status: "/SCSAT1/MAIN/OBC_1V8_Shunt_Status"
  - name: "/SCSAT1/MAIN/OBC_1V8_Bus"
    status: "/SCSAT1/MAIN/OBC_1V8_Bus_Status"
  - name: "/SCSAT1/MAIN/OBC_3V3_Shunt"
    status: "/SCSAT1/MAIN/OBC_3V3_Shunt_Status"
  - name: "/SCSAT1/MAIN/OBC_3V3_Bus"
    status: "/SCSAT1/MAIN/OBC_3V3_Bus_Status"
  - name: "/SCSAT1/MAIN/OBC_3V3_SYSA_Shunt"
    status: "/SCSAT1/MAIN/OBC_3V3_SYSA_Shunt_Status"
  - name: "/SCSAT1/MAIN/OBC_3V3_SYSA_Bus"
    status: "/SCSAT1/MAIN/OBC_3V3_SYSA_Bus_Status"
  - name: "/SCSAT1/MAIN/OBC_3V3_SYSB_Shunt"
    status: "/SCSAT1/MAIN/OBC_3V3_SYSB_Shunt_Status"
  - name: "/SCSAT1/MAIN/OBC_3V3_SYSB_Bus"
    status: "/SCSAT1/MAIN/OBC_3V3_SYSB_Bus_Status"
  - name: "/SCSAT1/MAIN/OBC_3V3_IO_Shunt"
    status: "/SCSAT1/MAIN/OBC_3V3_IO_Shunt_Status"
  - name: "/SCSAT1/MAIN/OBC_3V3_IO_Bus"
    status: "/SCSAT1/MAIN/OBC_3V3_IO_Bus_Status"
  - name: "/SCSAT1/MAIN/OBC_XADC_VCCINT"
    status: "/SCSAT1/MAIN/OBC_XADC_VCCINT_STATUS"
  - name: "/SCSAT1/MAIN/OBC_XADC_VCCAUX"
    status: "/SCSAT1/MAIN/OBC_XADC_VCCAUX_STATUS"
  - name: "/SCSAT1/MAIN/OBC_XADC_VCCBRAM"
    status: "/SCSAT1/MAIN/OBC_XADC_VCCBRAM_STATIS"
  - name: "/SCSAT1/MAIN/IO_PDU_04_3V3_Shunt"
    status: "/SCSAT1/MAIN/IO_PDU_04_3V3_Shunt_STATUS"
  - name: "/SCSAT1/MAIN/IO_PDU_04_3V3_Bus"
    status: "/SCSAT1/MAIN/IO_PDU_04_3V3_Bus_STATUS"
  - name: "/SCSAT1/MAIN/IO_VDD_3V3_SYS_Shunt"
    status: "/SCSAT1/MAIN/IO_VDD_3V3_SYS_Shunt_Status"
  - name: "/SCSAT1/MAIN/IO_VDD_3V3_SYS_Bus"
    status: "/SCSAT1/MAIN/IO_VDD_3V3_SYS_Bus_Status"
  - name: "/SCSAT1/MAIN/IO_VDD_3V3_Shunt"
    status: "/SCSAT1/MAIN/IO_VDD_3V3_Shunt_Status"
  - name: "/SCSAT1/MAIN/IO_VDD_3V3_Bus"
    status: "/SCSAT1/MAIN/IO_VDD_3V3_Bus_Status"
  - name: "/SCSAT1/MAIN/EPS_PING"
    status: "/SCSAT1/MAIN/EPS_PING_Status"
  - name: "/SCSAT1/MAIN/SRS3_PING"
    status: "/SCSAT1/MAIN/SRS3_PING_Status"
  - name: "/SCSAT1/MAIN/ADCS_PING"
    status: "/SCSAT1/MAIN/ADCS_PING_Status"
  - name: "/SCSAT1/MAIN/ZERO_PING"
    status: "/SCSAT1/MAIN/ZERO_PING_Status"
  - name: "/SCSAT1/MAIN/PICO_PING"
    status: "/SCSAT1/MAIN/PICO_PING_Status"
  - name: "/SCSAT1/MAIN/EPS_UPTIME"
    status: "/SCSAT1/MAIN/EPS_UPTIME_Status"
  - name: "/SCSAT1/MAIN/SRS3_UPTIME"
    status: "/SCSAT1/MAIN/SRS3_UPTIME_Status"
  - name: "/SCSAT1/MAIN/ADCS_UPTIME"
    status: "/SCSAT1/MAIN/ADCS_UPTIME_Status"
  - name: "/SCSAT1/MAIN/ZERO_UPTIME"
    status: "/SCSAT1/MAIN/ZERO_UPTIME_Status"
  - name: "/SCSAT1/MAIN/PICO_UPTIME"
    status: "/SCSAT1/MAIN/PICO_UPTIME_Status"
  - name: "/SCSAT1/MAIN/ZERO_TEMP"
    status: "/SCSAT1/MAIN/ZERO_TEMP_Status"
  - name: "/SCSAT1/MAIN/ZERO_FRAME_COUNT"
    status: "/SCSAT1/MAIN/ZERO_FRAME_COUNT_Status"
  - name: "/SCSAT1/MAIN/DSTRX3_HK_FREE_COUNT"
    status: "/SCSAT1/MAIN/DSTRX3_HK_Status"
  - name: "/SCSAT1/MAIN/DSTRX3_HK_WDT_COUNT"
    status: "/SCSAT1/MAIN/DSTRX3_HK_Status"
  - name: "/SCSAT1/MAIN/DSTRX3_HK_RSSI"
    status: "/SCSAT1/MAIN/DSTRX3_HK_Status"
  - name: "/SCSAT1/MAIN/DSTRX3_RECV_FREQ"
    status: "/SCSAT1/MAIN/DSTRX3_HK_Status"
  - name: "/SCSAT1/MAIN/DSTRX3_HK_VOLTAGE"
    status: "/SCSAT1/MAIN/DSTRX3_HK_Status"
  - name: "/SCSAT1/MAIN/DSTRX3_HK_TX_POWER"
    status: "/SCSAT1/MAIN/DSTRX3_HK_Status"
  - name: "/SCSAT1/MAIN/DSTRX3_HK_CARRIER_LOCK"
    status: "/SCSAT1/MAIN/DSTRX3_HK_Status"
  - name: "/SCSAT1/MAIN/DSTRX3_HK_SUB_CARRIER_LOCK"
    status: "/SCSAT1/MAIN/DSTRX3_HK_Status"
  - name: "/SCSAT1/MAIN/DSTRX3_HK_TX_POWER_SET"
    status: "/SCSAT1/MAIN/DSTRX3_HK_Status"
  - name: "/SCSAT1/MAIN/DSTRX3_HK_BIT_RATE_SET"
    status: "/SCSAT1/MAIN/DSTRX3_HK_Status"
  - name: "/SCSAT1/MAIN/DSTRX3_HK_PROGRAM_NO"
    status: "/SCSAT1/MAIN/DSTRX3_HK_Status"
  - name: "/SCSAT1/MAIN/DSTRX3_HK_CHECK_SUM"
    status: "/SCSAT1/MAIN/DSTRX3_HK_Status"
  - name: "/SCSAT1/MAIN/MGNM_X_PLUS_X_OUT"
    status: "/SCSAT1/MAIN/MGNM_X_PLUS_X_OUT_Status"
  - name: "/SCSAT1/MAIN/MGNM_X_PLUS_Y_OUT"
    status: "/SCSAT1/MAIN/MGNM_X_PLUS_Y_OUT_Status"
  - name: "/SCSAT1/MAIN/MGNM_X_PLUS_Z_OUT"
    status: "/SCSAT1/MAIN/MGNM_X_PLUS_Z_OUT_Status"
  - name: "/SCSAT1/MAIN/MGNM_X_MINUS_X_OUT"
    status: "/SCSAT1/MAIN/MGNM_X_MINUS_X_OUT_Status"
  - name: "/SCSAT1/MAIN/MGNM_X_MINUS_Y_OUT"
    status: "/SCSAT1/MAIN/MGNM_X_MINUS_Y_OUT_Status"
  - name: "/SCSAT1/MAIN/MGNM_X_MINUS_Z_OUT"
    status: "/SCSAT1/MAIN/MGNM_X_MINUS_Z_OUT_Status"
  - name: "/SCSAT1/MAIN/HWTEST_RESULT_SEQCOUNT"
  - name: "/SCSAT1/MAIN/HWTEST_LOOP_COUNT"
  - name: "/SCSAT1/MAIN/HWTEST_ERR_COUNT"
